# Site settings
# any variable of the format a: b, will be available as site.a, that can be
# used in headers/footers etc.
title: L3cube
email_gabhijit: gabhijit@gmail.com
name_gabhijit: Abhijit Gadgil
email_gsuryagandh: gaurav.suryagandh@gmail.com
name_gsuryagandh: Gaurav Suryagandh
description: > # this means to ignore newlines until "baseurl:"
  L3Cube blog on github.io 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  l3cube
# Build settings
markdown: kramdown
gaurav_suryagandh:
    name: Gaurav Suryagandh
abhijit_gadgil:
    name: Abhijit Gadgil
