# Site settings
title: L3cube
email: gabhijit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  L3Cube is team of programmers and technology evangalist. We 
  as a team have sound experties in System Programming(Applications and 
  Kernel), Networking, Storage, Full stack development and DevOps(Puppet, 
  ansible, saltstack, rundeck).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  l3cube

# Build settings
markdown: kramdown
